# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alan Glennon
tagline:          'Geographer 🎂  Angel'
description:      'Geographer'
url:              https://glennon.github.io
baseurl:          /

author:
  name:           'Alan Glennon'
  url:            https://twitter.com/glennon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/glennon
