title: Alan Glennon
logo:
author: GitHub User
email: glennon@myexampledomain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# social links
# twitter_username: glennon
# github_username:  glennon

show_excerpts: false # set to false to remove excerpts on the homepage
show_downloads: false

theme: jekyll-theme-minimal
