# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alan Glennon
tagline:          'Geographer 🎂  Angel'
description:      '<a href="https://cnn.com">About</a><br />
                  <a href="https://cnn.com">Articles</a><br />
                  <a href="https://cnn.com">Projects</a><br />
                  <a href="https://cnn.com">PhD Dissertation</a><br />
                  <a href="https://cnn.com">MSc Thesis</a><br />
                  '
url:              https://glennon.github.io
baseurl:          /

author:
  name:           'Alan Glennon'
  url:            https://twitter.com/glennon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/glennon
