# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alan Glennon
tagline:          'Geographer 🎂  Angel'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a>
                  theme (test test test) that pairs a prominent sidebar with uncomplicated content. Made by 
                  <a href="https://twitter.com/mdo" target="_blank">@mdo</a>. Test Test'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Alan Glennon'
  url:            https://twitter.com/glennon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/glennon
